[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && mkdir -p public"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_CACHE_DIR = ".pip-cache"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 